
version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=phone_number_app
  PhoneNumbersApi:
    image: 'phone-numbers-aps'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: PhoneNumbersApi
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/phone_number_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  java-ui:
    image: java-ui:0.0.1
    build: java-ui/
    ports:
      - "8081:8081"
    depends_on:
      - PhoneNumbersApi
