services:
  - type: web
    name: web
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: database
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: database
          property: password
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DB_HOST}:${SPRING_DB_PORT}/${SPRING_DB_DATABASE}

databases:
  - name: database
    region: frankfurt
    plan: free
